=begin
#Swiftype App Search API

#Swiftype App Search API

OpenAPI spec version: 0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'swiftype-app-search/api_client'
require 'swiftype-app-search/api_error'
require 'swiftype-app-search/version'
require 'swiftype-app-search/configuration'

# Models
require 'swiftype-app-search/models/deleted_status'
require 'swiftype-app-search/models/errors'
require 'swiftype-app-search/models/inline_response_200'
require 'swiftype-app-search/models/meta'
require 'swiftype-app-search/models/page'
require 'swiftype-app-search/models/synonym_set'

# APIs
require 'swiftype-app-search/api/synonyms_api'

module SwiftypeAppSearch
  class << self
    # Customize default settings for the SDK using block.
    #   SwiftypeAppSearch.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
