=begin
#Swiftype App Search API

#Swiftype App Search API

OpenAPI spec version: 0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

module SwiftypeAppSearch
  VERSION = "1.1.0"
end
