=begin
#Swiftype App Search API

#Swiftype App Search API

OpenAPI spec version: 0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwiftypeAppSearch::Errors
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Errors' do
  before do
    # run before each test
    @instance = SwiftypeAppSearch::Errors.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Errors' do
    it 'should create an instance of Errors' do
      expect(@instance).to be_instance_of(SwiftypeAppSearch::Errors)
    end
  end
  describe 'test attribute "errors"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

