=begin
#Swiftype App Search API

#Swiftype App Search API

OpenAPI spec version: 0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwiftypeAppSearch::Page
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Page' do
  before do
    # run before each test
    @instance = SwiftypeAppSearch::Page.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Page' do
    it 'should create an instance of Page' do
      expect(@instance).to be_instance_of(SwiftypeAppSearch::Page)
    end
  end
  describe 'test attribute "current"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "total_pages"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "total_results"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "size"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

